---
title: "philly_incedent_data"
output: html_document
date: "2023-10-23"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(sf)
library(tidyverse)
library(tidycensus)


root.dir = "https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/DATA/"
source("https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/functions.r")
```

```{r}
crime <- read.csv("incidents_part1_part2.csv")

crime.sf <- crime %>%
  na.omit() %>%
  st_as_sf(coords = c("lng", "lat"), crs = 4326, agr = "constant") %>%
  st_transform('ESRI:102728') %>%
  dplyr::select(cartodb_id, dispatch_date, dispatch_time, location_block, text_general_code)

crime.typed <- crime.sf %>%
  mutate(agg)

tracts00 <- 
  st_read(file.path(root.dir,"/Chapter1/PHL_CT00.geojson")) %>% 
    st_transform('ESRI:102728')

```

```{r}
ggplot() +
  geom_sf(data = tracts00, fill = "grey") +
  geom_sf(data = crime.sf,
          show.legend = "point", size = .01)
```

