---
title: "philly_incedent_data"
output: html_document
date: "2023-10-23"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(sf)
library(tidyverse)
library(tidycensus)
library(geojsonio)
library(jsonlite)

root.dir = "https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/DATA/"
source("https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/functions.r")
```

```{r}
crime <- read.csv("incidents_part1_part2.csv")

crime <- crime %>%
  na.omit() %>%
  dplyr::select(cartodb_id, dispatch_date, dispatch_time, location_block, text_general_code, lat, lng) %>%
  mutate(text_general_code = case_when(
         text_general_code == "Aggravated Assault Firearm" ~ "Aggravated Assault",
         text_general_code == "Aggravated Assault No Firearm" ~ "Aggravated Assault",
         text_general_code == "Burglary Non-Residential" ~ "Burglary",
         text_general_code == "Burglary Residential" ~ "Burglary",
         text_general_code == "Robbery Firearm" ~ "Robbery",
         text_general_code == "Robbery No Firearm" ~ "Robbery",
         text_general_code == "Theft from Vehicle" ~ "Thefts",
         text_general_code == "Thefts" ~ "Thefts",
         text_general_code == "Motor Vehicle Theft" ~ "Thefts",
         text_general_code == "Narcotic / Drug Law Violations" ~ "Drug Violations",
         text_general_code == "Fraud" ~ "Fraud",
         text_general_code == "Other Assaults" ~ "Other Assaults",
         text_general_code == "Vandalism/Criminal Mischief" ~ "Vandalism",
         text_general_code == "Weapon Violations" ~ "Weapon Violations",
         text_general_code == "Other Sex Offenses (Not Commercialized)" ~ "Sex Offenses",
         text_general_code == "Prostitution and Commercialized Vice" ~ "Sex Offenses",
         text_general_code == "Rape" ~ "Rape",
          .default = "Other Crimes"
  ))

crime_data <- toJSON(crime)
write(crime_data, file = "crimes.json")

tracts00 <- 
  st_read(file.path(root.dir,"/Chapter1/PHL_CT00.geojson")) %>% 
    st_transform('ESRI:102728')

```

```{r}
ggplot() +
  geom_sf(data = tracts00, fill = "grey") +
  geom_sf(data = crime.sf,
          show.legend = "point", size = .01)
```

